import styles from '../page.module.css';
import Image from 'next/image';
import ElementComment from '../../components/ui/ElementComment/ElementComment';
import anya from '../../../public/anya/anya.webp';

export default function About() {
	return (
		<div className={styles.page}>
			<h1 className={styles.title}>About me</h1>
			<p className={styles.textBlock}>
				My name is Victor Cherkashyn. I&apos;m a computer engineering student based in Lviv, Ukraine. 
				I spend my time learning, experimenting, and writing code because I enjoy it.
				Other interests include writing essays, reading books and traveling when possible.
			</p>
			<p className={styles.textBlock}>
				I&apos;m interested in how software works at different levels,
				from web applications to lower-level systems, and in how security and privacy fit into everyday tools.
				I tend to prefer simple, understandable solutions and software that respects users
				rather than trying to extract as much data as possible.
			</p>
			<p className={styles.textBlock}>
				Outside of personal projects and studying, I help run a local Linux user group chat. 
				It&apos;s a small community where people ask questions, share ideas, and help each other solve problems related to Linux and free software. 
				I care about FOSS not as an ideology, but as a practical way to build better, more transparent tools.
			</p>
			<p className={styles.textBlock}>
				My travels are focused around exploring urban areas of Ukraine. I&apos;ve been
				to several cities and towns, enjoying local culture and architecture, in the case of cities
				in Western Ukraine. Although, ther&apos;s a lot of architecture to see in other regions too.	
			</p>
			<p className={styles.textBlock}>
				I don&apos;t have any pets at the moment but my travels usually facilitate meeting
				a lot of street cats. 
				I have an <a href="https://metapixl.com/vittorio" className={styles.link}>account</a> on
				Pixelfed that I use to post pictures of
				cats I meet during my trips.	
			</p>
			<p>
				I plan to keep this site as a personal space for essays focusing on technology.
				In the future, I might create a separate blog for posts about videogames and other
				geek stuff.
			</p>
			<p className={styles.textBlock}>
				This site is mostly a place to keep track of things I&apos;ve worked on and topics 
				I&apos;m interested in. If you want something more concrete, the projects page 
				is a better starting point.
			</p>
			<p className={styles.textBlock}>
				My blog also features an original character, Anya:
			</p>
			<ElementComment comment="Anya was inspired by a cover of a Ukrainian Soviet-era magazine, Perets.">
				<Image src={anya} alt="Anya, a girl in Ukrainian traditional clothing with PPSh-43 on her shoulder." placeholder='blur' width={400}/>
			</ElementComment>
			<p className={styles.textBlock}>
				She was generated by Google&apos;s Nano Banana but I want to hire
				an artist to draw her properly in the future. I already have someone in mind.
			</p>
		</div>
	);
}
