import type { Metadata } from 'next';
import styles from './layout.module.css';
import Link from 'next/link';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={styles.body}>
				<nav>
					<ul>
						<li>
							<Link href='/'>Home</Link>
						</li>
						<li>
							<Link href='/blog'>Blog</Link>
						</li>
						<li>
							<Link href='/projects'>Projects</Link>
						</li>
						<li>
							<Link href='/about'>About me</Link>
						</li>
					</ul>
				</nav>
				<main>{children}</main>
				<footer className={styles.footer}>
					Made with coffee and tea and love and Next and many other
					things
				</footer>
			</body>
		</html>
	);
}
