import type { Metadata } from 'next';
import styles from './layout.module.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={styles.body}>
				<main>{children}</main>
				<footer className={styles.footer}>
					Made with coffee and tea love and Next and many other things
				</footer>
			</body>
		</html>
	);
}
